# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2bc19d14d7fcb5b4c938a4af967a48aa124f85b08dab8803e6b46cb5e4b6f4ff4148aa176e08a5db04cf1ee416fcc5e4e16058ccf88c514d04e749b12db53c

test:
  secret_key_base: be45981e08ed34e796e13a4cf18c8f40c6292bb3b5fe31858ed7992c4b0481b5b181fc8b6432543b3ae86139e4651adcc72f37adff63e9ec9928cd0b31c7f5ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
